### ISSUE TITLE
Request to release for ROS Kinetic

### ISSUE THREAD

**Issue by 130s** [ros-drivers/urg_node#21]
Thanks!

Btw I see it's released for Jade so #11 should be closed.

**Comment by doisyg** [comment]
+1 
a release for kinetic would be really nice

**Comment by stwirth** [comment]
+1

**Comment by 130s** [comment]
@tfoote could you take care of this? It's been 2weeks+ and no response is heard.

**Comment by tfoote** [comment]
I tried blooming it but this depends on laser_proc which is not yet released.

**Comment by kmhallen** [comment]
We might want to merge #13 first.

**Comment by schvarcz** [comment]
+1

**Comment by tonybaltovski** [comment]
+1

**Comment by jack-oquin** [comment]
+1

**Comment by schvarcz** [comment]
Just a input for this issue.

I am using the pkg available at ubuntu repository for kinetic (sudo apt-get install ros-kinetic-urg-node) for get data from my Hokuyo URG 04LX and it is workinng as a charm.

So maybe they do not put the code for kinetic in this repository, maybe they are using the indigo branch or maybe my computer is a time travel machine that is able to download code not yet available!!!! 

I just know it is working great with ROS Kinetic. So, as they took time to close the same issue for ROS Jade, I strongly think that they solve the issue here, but did not close it yet....

For the next souls looking for this pkg to ROS, it is already available.

**Comment by kmhallen** [comment]
Yes, there is a release for Kinetic.   
https://discourse.ros.org/t/new-packages-for-kinetic-2016-10-04/544

However, Kinetic users still do not have access to the ```getID``` program. PR #13 has not been merged, and the [hokuyo_node](http://wiki.ros.org/hokuyo_node) package that also has getID is EOL.

**Comment by tonybaltovski** [comment]
Released!

**Comment by kmhallen** [comment]
Thanks!
